# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-07-24 05:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LockDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('lock_user', models.OneToOneField(help_text='Locked user', on_delete=django.db.models.deletion.CASCADE, related_name='lockdownuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
